rvm:
  - 2.0
  - 2.1
  - 2.2.2
  - jruby-19mode
  - rbx-2

script: "bundle exec rake clean spec"

gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile

matrix:
  fast_finish: true

sudo: false
cache: bundler
